# Generated by Django 3.0.1 on 2019-12-29 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hero',
            name='services_hero',
        ),
    ]
