# Generated by Django 3.0.1 on 2019-12-30 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0003_services'),
    ]

    operations = [
        migrations.CreateModel(
            name='Why',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subtitle_why', models.CharField(max_length=250, verbose_name='Заголовок')),
                ('name_why', models.CharField(max_length=150, verbose_name='Название')),
                ('text_why', models.CharField(max_length=250, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Почему мы?',
                'verbose_name_plural': 'Почему мы?',
            },
        ),
    ]
