# Generated by Django 3.0.1 on 2020-01-06 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0005_remove_why_subtitle_why'),
    ]

    operations = [
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_work', models.ImageField(blank=True, default='', upload_to='mainpage/work', verbose_name='Фотография')),
                ('text_work', models.CharField(max_length=250, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Работа',
                'verbose_name_plural': 'Работа',
            },
        ),
        migrations.AlterField(
            model_name='hero',
            name='image_hero',
            field=models.ImageField(blank=True, default='', upload_to='mainpage/hero', verbose_name='Изображение'),
        ),
    ]
